from __future__ import annotations

import os
import random

from reportlab.lib.colors import HexColor, black
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


CLINIC_NAMES = (
    "Sunrise Medical Center",
    "TruHeal Clinic",
    "Apollo Family Care",
    "MedSyn Health Hub",
    "St. Mary's Health Point",
)

FORM_LABELS = {
    "Prescription Form": ("Patient Details", "Clinical Notes", "Prescription", "Advice"),
    "Patient Intake Form": ("Patient Details", "Reason for Visit", "Allergies", "Insurance"),
    "Lab Request Form": ("Patient Details", "Clinical Notes", "Requested Tests", "Physician"),
}


def _draw_paper_texture(c: canvas.Canvas, width: float, height: float) -> None:
    c.setFillColor(HexColor("#fbfaf6"))
    c.rect(0, 0, width, height, stroke=0, fill=1)
    c.setStrokeColor(HexColor("#ece7dc"))
    c.setLineWidth(0.25)
    for _ in range(80):
        x = random.uniform(0, width)
        y = random.uniform(0, height)
        c.line(x, y, x + random.uniform(-12, 12), y + random.uniform(-3, 3))


def _draw_header(c: canvas.Canvas, width: float, height: float, form_type: str) -> None:
    accent = HexColor("#27745f")
    c.setFillColor(accent)
    c.roundRect(0.45 * inch, height - 1.25 * inch, width - 0.9 * inch, 0.78 * inch, 8, stroke=0, fill=1)
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 22)
    c.drawString(0.7 * inch, height - 0.82 * inch, random.choice(CLINIC_NAMES))
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 0.7 * inch, height - 0.72 * inch, form_type)
    c.drawRightString(width - 0.7 * inch, height - 0.93 * inch, "Synthetic data - not a real patient record")


def _draw_form_lines(c: canvas.Canvas, width: float, height: float, form_type: str) -> None:
    labels = FORM_LABELS.get(form_type, FORM_LABELS["Prescription Form"])
    left = 0.55 * inch
    top = height - 1.65 * inch
    box_width = width - 1.1 * inch
    row_height = 1.18 * inch

    c.setStrokeColor(HexColor("#78a99a"))
    c.setLineWidth(1.2)
    c.roundRect(left, 1.55 * inch, box_width, top - 1.55 * inch, 6, stroke=1, fill=0)

    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(HexColor("#27745f"))
    y = top - 0.35 * inch
    for label in labels:
        c.drawString(left + 0.22 * inch, y, label.upper())
        c.setStrokeColor(HexColor("#d7e4df"))
        c.line(left + 0.22 * inch, y - 0.12 * inch, left + box_width - 0.22 * inch, y - 0.12 * inch)
        y -= row_height


def generate_medical_form(
    handwriting_image: str,
    signature_image: str | None,
    pdf_path: str,
    patient: dict[str, object] | None = None,
    form_type: str = "Prescription Form",
) -> None:
    os.makedirs(os.path.dirname(pdf_path) or ".", exist_ok=True)
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    _draw_paper_texture(c, width, height)
    _draw_header(c, width, height, form_type)
    _draw_form_lines(c, width, height, form_type)

    if os.path.exists(handwriting_image):
        c.drawImage(
            handwriting_image,
            1.0 * inch,
            2.25 * inch,
            width=width - 2.0 * inch,
            height=4.75 * inch,
            preserveAspectRatio=True,
            mask="auto",
        )

    c.setStrokeColor(HexColor("#78a99a"))
    c.setLineWidth(1)
    c.line(width - 2.65 * inch, 1.2 * inch, width - 0.75 * inch, 1.2 * inch)

    if signature_image and os.path.exists(signature_image):
        c.drawImage(signature_image, width - 2.65 * inch, 1.25 * inch, width=1.8 * inch, height=0.55 * inch, preserveAspectRatio=True, mask="auto")

    c.setFont("Helvetica", 8)
    c.setFillColor(black)
    doctor = patient.get("doctor", "Synthetic Physician") if patient else "Synthetic Physician"
    c.drawRightString(width - 0.75 * inch, 0.92 * inch, str(doctor))
    c.drawString(0.55 * inch, 0.55 * inch, "Generated by MedSyn Form System | Synthetic sample only")
    c.save()


def generate_prescription(patient_image: str, signature_image: str | None, pdf_path: str) -> None:
    generate_medical_form(patient_image, signature_image, pdf_path, form_type="Prescription Form")
