from __future__ import annotations

import os
import random

from reportlab.lib.colors import HexColor, black, green
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


CLINIC_NAMES = (
    "Sunrise Medical Center",
    "TruHeal Clinic",
    "Apollo Family Care",
    "MedSyn Health Hub",
    "St. Mary's Health Point",
)

FORM_LABELS = {
    "Prescription Form": ("Name", "Date of Birth", "Main Complaint", "Diagnosis", "Medications", "Advice"),
    "Patient Intake Form": ("Name", "Date of Birth", "Reason for Visit", "Allergies", "Insurance", "Visit Date"),
    "Lab Request Form": ("Patient", "Date of Birth", "Clinical Note", "Symptoms", "Requested Tests", "Physician"),
}


def _draw_original_style_form(c: canvas.Canvas, width: float, height: float, form_type: str) -> tuple[float, float, float, float]:
    labels = FORM_LABELS.get(form_type, FORM_LABELS["Prescription Form"])
    border_margin = 0.4 * inch
    inner_margin = 0.3 * inch
    header_height = 1.3 * inch

    c.setFillColor(HexColor("#ffffff"))
    c.rect(0, 0, width, height, stroke=0, fill=1)

    c.setLineWidth(3)
    c.setStrokeColor(black)
    c.rect(border_margin, border_margin, width - 2 * border_margin, height - 1.5 * border_margin)

    c.setLineWidth(2.5)
    c.setStrokeColor(green)
    c.rect(
        border_margin + inner_margin,
        height - border_margin - header_height,
        width - 2 * (border_margin + inner_margin),
        header_height,
    )

    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(green)
    c.drawCentredString(width / 2, height - border_margin - header_height / 2 + 10, random.choice(CLINIC_NAMES))
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, height - border_margin - header_height / 2 - 13, f"{form_type} | Synthetic data")

    content_y_top = height - border_margin - 1.2 * header_height + 1.8 * inner_margin
    content_height = content_y_top - border_margin - 2 * inch
    content_x = border_margin + inner_margin
    content_y = border_margin + 1.5 * inch
    content_width = width - 2 * (border_margin + inner_margin)

    c.setLineWidth(2)
    c.setStrokeColor(green)
    c.rect(content_x, content_y, content_width, content_height)

    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(green)
    label_x = border_margin + 0.82 * inch
    y = content_y_top - 1.2 * inch
    gap = 0.72 * inch
    for label in labels:
        c.drawString(label_x, y, f"{label}:")
        y -= gap

    footer_height = 1 * inch
    c.setLineWidth(2)
    c.setStrokeColor(green)
    c.rect(
        border_margin + inner_margin,
        border_margin + inner_margin,
        width - 2 * (border_margin + inner_margin),
        footer_height,
    )

    return content_x, content_y, content_width, content_height


def _draw_handwriting_image(c: canvas.Canvas, handwriting_image: str, content_box: tuple[float, float, float, float]) -> None:
    if not os.path.exists(handwriting_image):
        return

    content_x, content_y, content_width, content_height = content_box
    image_x = content_x + 2.0 * inch
    image_y = content_y + 1.05 * inch
    image_width = content_width - 2.35 * inch
    image_height = 3.75 * inch

    c.drawImage(
        handwriting_image,
        image_x,
        image_y,
        width=image_width,
        height=image_height,
        preserveAspectRatio=True,
        anchor="nw",
        mask="auto",
    )


def generate_medical_form(
    handwriting_image: str,
    signature_image: str | None,
    pdf_path: str,
    patient: dict[str, object] | None = None,
    form_type: str = "Prescription Form",
) -> None:
    os.makedirs(os.path.dirname(pdf_path) or ".", exist_ok=True)
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    content_box = _draw_original_style_form(c, width, height, form_type)
    _draw_handwriting_image(c, handwriting_image, content_box)

    c.setStrokeColor(HexColor("#78a99a"))
    c.setLineWidth(1)
    c.line(width - 2.65 * inch, 1.2 * inch, width - 0.75 * inch, 1.2 * inch)

    if signature_image and os.path.exists(signature_image):
        c.drawImage(signature_image, width - 2.65 * inch, 1.25 * inch, width=1.8 * inch, height=0.55 * inch, preserveAspectRatio=True, mask="auto")

    c.setFont("Helvetica", 8)
    c.setFillColor(black)
    doctor = patient.get("doctor", "Synthetic Physician") if patient else "Synthetic Physician"
    c.drawRightString(width - 0.75 * inch, 0.92 * inch, str(doctor))
    c.drawString(0.55 * inch, 0.55 * inch, "Generated by MedSyn Form System | Synthetic sample only")
    c.save()


def generate_prescription(patient_image: str, signature_image: str | None, pdf_path: str) -> None:
    generate_medical_form(patient_image, signature_image, pdf_path, form_type="Prescription Form")
