from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.colors import green, black
import random
import os

# === Random Clinic Names ===
clinic_names = [
    "Sunrise Medical Center",
    "TruHeal Clinic",
    "Apollo Family Care",
    "MedSyn Health Hub",
    "St. Mary’s Health Point"
]

def generate_prescription(patient_image, signature_image, pdf_path):
    """Generate a single synthetic prescription PDF."""
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    border_margin = 0.4 * inch
    inner_margin = 0.3 * inch

    # === Outer Border ===
    c.setLineWidth(3)
    c.setStrokeColor(black)
    c.rect(border_margin, border_margin, width - 2 * border_margin, height - 1.5 * border_margin)

    # === Header (Clinic Name) ===
    header_height = 1.3 * inch
    c.setLineWidth(2.5)
    c.setStrokeColor(green)
    c.rect(border_margin + inner_margin, height - border_margin - header_height,
           width - 2 * (border_margin + inner_margin), header_height)
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(green)
    clinic_name = random.choice(clinic_names)
    c.drawCentredString(width / 2, height - border_margin - header_height / 2 + 6, clinic_name)

    # === Content Box ===
    content_y_top = height - border_margin - 1.2 * header_height + 1.8 * inner_margin
    content_height = content_y_top - border_margin - 2 * inch
    c.setLineWidth(2)
    c.setStrokeColor(green)
    c.rect(border_margin + inner_margin, border_margin + 1.5 * inch,
           width - 2 * (border_margin + inner_margin), content_height)

    # === Field Labels ===
    labels = ["Name", "Date of Birth", "Main Complaint", "Allergies", "Medications", "Insurance"]
    label_x = border_margin + 1 * inch
    image_x = width / 2.5
    start_y = content_y_top - 1.5 * inch
    gap = 0.8 * inch

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(green)
    y = start_y
    for label in labels:
        c.drawString(label_x, y, label + ":")
        y -= gap

    # === Patient Image ===
    if os.path.exists(patient_image):
        image_width = 4.1 * inch
        image_height = len(labels) * gap * 1.2
        c.drawImage(patient_image, image_x, start_y - image_height + 0.8 * inch,
                    width=image_width, height=image_height, mask='auto')

    # === Footer (Doctor Signature) ===
    footer_height = 1 * inch
    c.setLineWidth(2)
    c.setStrokeColor(green)
    c.rect(border_margin + inner_margin, border_margin + inner_margin,
           width - 2 * (border_margin + inner_margin), footer_height)

    if signature_image and os.path.exists(signature_image):
        sig_w = 2.5 * inch
        sig_h = 0.7 * inch
        sig_x = width - border_margin - inner_margin - sig_w - 0.2 * inch
        sig_y = border_margin + inner_margin + 0.15 * inch
        c.drawImage(signature_image, sig_x, sig_y, width=sig_w, height=sig_h, mask='auto')

    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(black)
    c.drawString(border_margin + inner_margin, border_margin + inner_margin / 2,
                 "Generated by MedSyn Form System")

    c.save()
